### ISSUE TITLE
Required arguments

### ISSUE THREAD

**Issue by sjbeskur** [storyfeet/clap_conf#1]
Very nice work @storyfeet ... is there a clean way to enforce required arguments?  It seems that you cannot use ".required(true)"  when creating clap matches Args.   Put another way... if an argument is not specified in either the config, environment variable, or as a command line arg can you still show the standard error / usage message that clap provides.

**Comment by storyfeet** [comment]
I've recently added a "req" method on the grabber, not sure if that's been added here yet.  Which returns a result with an error if not supplied. So you can use that as a mechanism. 

One of the problems, is that (for better or worse) I made this quite generic, to allow for people using Json config files if they preferred. etc.

So there are a couple of options. One is an .on_not provided type method that takes a closure.

I guess you can do 
```rust
cfg.grab().arg("ARGNAME")
                .conf("CONFNAME")
                .env("ENVNAME")
                .req()
                .map_err(|e| {clap.show_usage(); e} )?;
```
Not super tidy but the other option means making the wrapper more messy than it already is.

That said I'm open to ideas on how to make it better if you have them

**Comment by sjbeskur** [comment]
ahh.. perfect.   I think this will work.   I don't see the .req() on the 0.1.2 crate but I'll keep an eye out for it.  Not sure I have any ideas on how you would do this any better without writing your own command line parsing library that has this support built in, but I like what you've done.

**Comment by storyfeet** [comment]
Version 0.1.3 is now up. 

Glad you like it.  It current;y doesn't show docs on crates.io, but I believe that will come shortly

Thanks.
